apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: foo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v0.14.3
    helm.sh/chart: external-secrets-0.14.3
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: foo-external-secrets-edit
rules:
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - secretstores
  - clustersecretstores
  - pushsecrets
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - generators.external-secrets.io
  resources:
  - acraccesstokens
  - clustergenerators
  - ecrauthorizationtokens
  - fakes
  - gcraccesstokens
  - githubaccesstokens
  - quayaccesstokens
  - passwords
  - vaultdynamicsecrets
  - webhooks
  - grafanas
  - generatorstates
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
